### ISSUE TITLE
File session drivers doesn't work properly

### ISSUE THREAD

**Issue by Eredrim** [fuelphp/fuelphp#76]
I have a fuelphp 1.8 installation and I need to use the file session driver. However, the fuelfid changes on each page and then, a file is created on each page visited. I don't have this problem with the cookie driver, the fuelcid stays the same all the time.

The session class is added to the alway_load part in the config file and the session.php config file was copied in app directory and only modified to use file driver.

**Comment by WanWizard** [comment]
With the cookie driver, the session data is in the cookie, so the content can't stay the same, unless you don't store anything?

This smells a bit like a file permission issue, the app can't read the session file, so it creates a new session file? Otherwise, for all other session types, the session id is rotated (by default) every 5 minutes, which for file based sessions means a new file will be created. Garbage collection will take care of cleaning up stale files, which is triggered on average on 5% (by default) of the page requests. 

All default values can be adjusted in the session config file.

**Comment by Eredrim** [comment]
I rectify what I said: it works with the cookie driver, effectively the fuelcid is not the same.

With the file session driver, it is not a file permissions issue. I granted all rights on the session files folder and I am on Windows (only for development stage). It is not also a problem of garbage collection : a file is created each time I press the F5 key on my index page.

**Comment by WanWizard** [comment]
Ok.

First, make sure you have correctly defined the timezones. The server timezone must match the timezone in your php.ini, and in your application config file. If those are wrong (say your server is running GMT-6, but the app in UTC), the cookie might already be expired when it reaches your browser (since by default it has a 2 hour expiry). Check the expiry timestamp on the session cookie in your browser with some browser extension tool, to make sure it is not expired.

If this is all ok, you will have to do some debugging yourself since I don't use Windows, and have no problems here.

First, upgrade our installation to 1.9/develop to make sure you have the latest code.Then enable all logging in your application config (use Fuel::L_ALL), they enables some debug messages in the session classes, and disable session cookie encryption in your application session config (encrypt_cookie = false). This allows you to see the session id inside the cookie, so you can match it with the file.

Now you can debug the Session_File class `read()` method. Check if it gets the correct session id, check if it can read the session file correctly, check your logs for any debug messages.

**Comment by axelitus** [comment]
It seems strange. I have worked with Session and file session driver on Windows (using XAMPP for easier setup and happily not anymore!) and haven't had this issue. I agree with @WanWizard in that it could be a timezone difference issue, seems as when the session file/cookie is issued, it is not longer valid at the "same" instance and that could mean an issue with time differences and how they are interpreted by each layer on your server/interpreter/app and thus they should match on all cases.

**Comment by Eredrim** [comment]
After a quick composer self-update followed by a composer update, it seems to be working fine. It is strange... Finally it was not a server time problem. Many thanks for your help.

**Comment by axelitus** [comment]
Odd, but good thing it's working now! ;)
